VkFramebufferCreateFlags :: VkFlags;
VkQueryPoolCreateFlags :: VkFlags;
VkRenderPassCreateFlags :: VkFlags;
VkSamplerCreateFlags :: VkFlags;
VkPipelineLayoutCreateFlags :: VkFlags;
VkPipelineCacheCreateFlags :: VkFlags;
VkPipelineDepthStencilStateCreateFlags :: VkFlags;
VkPipelineDynamicStateCreateFlags :: VkFlags;
VkPipelineColorBlendStateCreateFlags :: VkFlags;
VkPipelineMultisampleStateCreateFlags :: VkFlags;
VkPipelineRasterizationStateCreateFlags :: VkFlags;
VkPipelineViewportStateCreateFlags :: VkFlags;
VkPipelineTessellationStateCreateFlags :: VkFlags;
VkPipelineInputAssemblyStateCreateFlags :: VkFlags;
VkPipelineVertexInputStateCreateFlags :: VkFlags;
VkPipelineShaderStageCreateFlags :: VkFlags;
VkDescriptorSetLayoutCreateFlags :: VkFlags;
VkBufferViewCreateFlags :: VkFlags;
VkInstanceCreateFlags :: VkFlags;
VkDeviceCreateFlags :: VkFlags;
VkDeviceQueueCreateFlags :: VkFlags;
VkQueueFlags :: VkFlags;
VkMemoryPropertyFlags :: VkFlags;
VkMemoryHeapFlags :: VkFlags;
VkAccessFlags :: VkFlags;
VkBufferUsageFlags :: VkFlags;
VkBufferCreateFlags :: VkFlags;
VkShaderStageFlags :: VkFlags;
VkImageUsageFlags :: VkFlags;
VkImageCreateFlags :: VkFlags;
VkImageViewCreateFlags :: VkFlags;
VkPipelineCreateFlags :: VkFlags;
VkColorComponentFlags :: VkFlags;
VkFenceCreateFlags :: VkFlags;
VkSemaphoreCreateFlags :: VkFlags;
VkFormatFeatureFlags :: VkFlags;
VkQueryControlFlags :: VkFlags;
VkQueryResultFlags :: VkFlags;
VkShaderModuleCreateFlags :: VkFlags;
VkEventCreateFlags :: VkFlags;
VkCommandPoolCreateFlags :: VkFlags;
VkCommandPoolResetFlags :: VkFlags;
VkCommandBufferResetFlags :: VkFlags;
VkCommandBufferUsageFlags :: VkFlags;
VkQueryPipelineStatisticFlags :: VkFlags;
VkMemoryMapFlags :: VkFlags;
VkMemoryUnmapFlags :: VkFlags;
VkMemoryUnmapFlagsKHR :: VkMemoryUnmapFlags;
VkImageAspectFlags :: VkFlags;
VkSparseMemoryBindFlags :: VkFlags;
VkSparseImageFormatFlags :: VkFlags;
VkSubpassDescriptionFlags :: VkFlags;
VkPipelineStageFlags :: VkFlags;
VkSampleCountFlags :: VkFlags;
VkAttachmentDescriptionFlags :: VkFlags;
VkStencilFaceFlags :: VkFlags;
VkCullModeFlags :: VkFlags;
VkDescriptorPoolCreateFlags :: VkFlags;
VkDescriptorPoolResetFlags :: VkFlags;
VkDependencyFlags :: VkFlags;
VkSubgroupFeatureFlags :: VkFlags;
VkIndirectCommandsLayoutUsageFlagsNV :: VkFlags;
VkIndirectStateFlagsNV :: VkFlags;
VkGeometryFlagsKHR :: VkFlags;
VkGeometryFlagsNV :: VkGeometryFlagsKHR;
VkGeometryInstanceFlagsKHR :: VkFlags;
VkGeometryInstanceFlagsNV :: VkGeometryInstanceFlagsKHR;
VkClusterAccelerationStructureGeometryFlagsNV :: VkFlags;
VkClusterAccelerationStructureClusterFlagsNV :: VkFlags;
VkClusterAccelerationStructureAddressResolutionFlagsNV :: VkFlags;
VkBuildAccelerationStructureFlagsKHR :: VkFlags;
VkBuildAccelerationStructureFlagsNV :: VkBuildAccelerationStructureFlagsKHR;
VkPrivateDataSlotCreateFlags :: VkFlags;
VkPrivateDataSlotCreateFlagsEXT :: VkPrivateDataSlotCreateFlags;
VkAccelerationStructureCreateFlagsKHR :: VkFlags;
VkDescriptorUpdateTemplateCreateFlags :: VkFlags;
VkDescriptorUpdateTemplateCreateFlagsKHR :: VkDescriptorUpdateTemplateCreateFlags;
VkPipelineCreationFeedbackFlags :: VkFlags;
VkPipelineCreationFeedbackFlagsEXT :: VkPipelineCreationFeedbackFlags;
VkPerformanceCounterDescriptionFlagsKHR :: VkFlags;
VkAcquireProfilingLockFlagsKHR :: VkFlags;
VkSemaphoreWaitFlags :: VkFlags;
VkSemaphoreWaitFlagsKHR :: VkSemaphoreWaitFlags;
VkPipelineCompilerControlFlagsAMD :: VkFlags;
VkShaderCorePropertiesFlagsAMD :: VkFlags;
VkDeviceDiagnosticsConfigFlagsNV :: VkFlags;
VkRefreshObjectFlagsKHR :: VkFlags;
VkAccessFlags2 :: VkFlags64;
VkAccessFlags2KHR :: VkAccessFlags2;
VkPipelineStageFlags2 :: VkFlags64;
VkPipelineStageFlags2KHR :: VkPipelineStageFlags2;
VkAccelerationStructureMotionInfoFlagsNV :: VkFlags;
VkAccelerationStructureMotionInstanceFlagsNV :: VkFlags;
VkFormatFeatureFlags2 :: VkFlags64;
VkFormatFeatureFlags2KHR :: VkFormatFeatureFlags2;
VkRenderingFlags :: VkFlags;
VkMemoryDecompressionMethodFlagsNV :: VkFlags64;
VkRenderingFlagsKHR :: VkRenderingFlags;
VkBuildMicromapFlagsEXT :: VkFlags;
VkMicromapCreateFlagsEXT :: VkFlags;
VkIndirectCommandsLayoutUsageFlagsEXT :: VkFlags;
VkIndirectCommandsInputModeFlagsEXT :: VkFlags;
VkDirectDriverLoadingFlagsLUNARG :: VkFlags;
VkPipelineCreateFlags2 :: VkFlags64;
VkPipelineCreateFlags2KHR :: VkPipelineCreateFlags2;
VkBufferUsageFlags2 :: VkFlags64;
VkBufferUsageFlags2KHR :: VkBufferUsageFlags2;
VkTensorCreateFlagsARM :: VkFlags64;
VkTensorUsageFlagsARM :: VkFlags64;
VkTensorViewCreateFlagsARM :: VkFlags64;
VkDataGraphPipelineSessionCreateFlagsARM :: VkFlags64;
VkDataGraphPipelineDispatchFlagsARM :: VkFlags64;
VkCompositeAlphaFlagsKHR :: VkFlags;
VkDisplayPlaneAlphaFlagsKHR :: VkFlags;
VkSurfaceTransformFlagsKHR :: VkFlags;
VkSwapchainCreateFlagsKHR :: VkFlags;
VkDisplayModeCreateFlagsKHR :: VkFlags;
VkDisplaySurfaceCreateFlagsKHR :: VkFlags;
VkAndroidSurfaceCreateFlagsKHR :: VkFlags;
VkViSurfaceCreateFlagsNN :: VkFlags;
VkWaylandSurfaceCreateFlagsKHR :: VkFlags;
VkWin32SurfaceCreateFlagsKHR :: VkFlags;
VkXlibSurfaceCreateFlagsKHR :: VkFlags;
VkXcbSurfaceCreateFlagsKHR :: VkFlags;
VkDirectFBSurfaceCreateFlagsEXT :: VkFlags;
VkIOSSurfaceCreateFlagsMVK :: VkFlags;
VkMacOSSurfaceCreateFlagsMVK :: VkFlags;
VkMetalSurfaceCreateFlagsEXT :: VkFlags;
VkImagePipeSurfaceCreateFlagsFUCHSIA :: VkFlags;
VkStreamDescriptorSurfaceCreateFlagsGGP :: VkFlags;
VkHeadlessSurfaceCreateFlagsEXT :: VkFlags;
VkScreenSurfaceCreateFlagsQNX :: VkFlags;
VkPeerMemoryFeatureFlags :: VkFlags;
VkPeerMemoryFeatureFlagsKHR :: VkPeerMemoryFeatureFlags;
VkMemoryAllocateFlags :: VkFlags;
VkMemoryAllocateFlagsKHR :: VkMemoryAllocateFlags;
VkDeviceGroupPresentModeFlagsKHR :: VkFlags;
VkDebugReportFlagsEXT :: VkFlags;
VkCommandPoolTrimFlags :: VkFlags;
VkCommandPoolTrimFlagsKHR :: VkCommandPoolTrimFlags;
VkExternalMemoryHandleTypeFlagsNV :: VkFlags;
VkClusterAccelerationStructureIndexFormatFlagsNV :: VkFlags;
VkExternalMemoryFeatureFlagsNV :: VkFlags;
VkExternalMemoryHandleTypeFlags :: VkFlags;
VkExternalMemoryHandleTypeFlagsKHR :: VkExternalMemoryHandleTypeFlags;
VkExternalMemoryFeatureFlags :: VkFlags;
VkExternalMemoryFeatureFlagsKHR :: VkExternalMemoryFeatureFlags;
VkExternalSemaphoreHandleTypeFlags :: VkFlags;
VkExternalSemaphoreHandleTypeFlagsKHR :: VkExternalSemaphoreHandleTypeFlags;
VkExternalSemaphoreFeatureFlags :: VkFlags;
VkExternalSemaphoreFeatureFlagsKHR :: VkExternalSemaphoreFeatureFlags;
VkSemaphoreImportFlags :: VkFlags;
VkSemaphoreImportFlagsKHR :: VkSemaphoreImportFlags;
VkExternalFenceHandleTypeFlags :: VkFlags;
VkExternalFenceHandleTypeFlagsKHR :: VkExternalFenceHandleTypeFlags;
VkExternalFenceFeatureFlags :: VkFlags;
VkExternalFenceFeatureFlagsKHR :: VkExternalFenceFeatureFlags;
VkFenceImportFlags :: VkFlags;
VkFenceImportFlagsKHR :: VkFenceImportFlags;
VkSurfaceCounterFlagsEXT :: VkFlags;
VkPipelineViewportSwizzleStateCreateFlagsNV :: VkFlags;
VkPipelineDiscardRectangleStateCreateFlagsEXT :: VkFlags;
VkPipelineCoverageToColorStateCreateFlagsNV :: VkFlags;
VkPipelineCoverageModulationStateCreateFlagsNV :: VkFlags;
VkPipelineCoverageReductionStateCreateFlagsNV :: VkFlags;
VkValidationCacheCreateFlagsEXT :: VkFlags;
VkDebugUtilsMessageSeverityFlagsEXT :: VkFlags;
VkDebugUtilsMessageTypeFlagsEXT :: VkFlags;
VkDebugUtilsMessengerCreateFlagsEXT :: VkFlags;
VkDebugUtilsMessengerCallbackDataFlagsEXT :: VkFlags;
VkDeviceMemoryReportFlagsEXT :: VkFlags;
VkPipelineRasterizationConservativeStateCreateFlagsEXT :: VkFlags;
VkDescriptorBindingFlags :: VkFlags;
VkDescriptorBindingFlagsEXT :: VkDescriptorBindingFlags;
VkConditionalRenderingFlagsEXT :: VkFlags;
VkResolveModeFlags :: VkFlags;
VkResolveModeFlagsKHR :: VkResolveModeFlags;
VkPipelineRasterizationStateStreamCreateFlagsEXT :: VkFlags;
VkPipelineRasterizationDepthClipStateCreateFlagsEXT :: VkFlags;
VkSwapchainImageUsageFlagsANDROID :: VkFlags;
VkToolPurposeFlags :: VkFlags;
VkToolPurposeFlagsEXT :: VkToolPurposeFlags;
VkSubmitFlags :: VkFlags;
VkSubmitFlagsKHR :: VkSubmitFlags;
VkImageFormatConstraintsFlagsFUCHSIA :: VkFlags;
VkHostImageCopyFlags :: VkFlags;
VkHostImageCopyFlagsEXT :: VkHostImageCopyFlags;
VkPartitionedAccelerationStructureInstanceFlagsNV :: VkFlags;
VkImageConstraintsInfoFlagsFUCHSIA :: VkFlags;
VkGraphicsPipelineLibraryFlagsEXT :: VkFlags;
VkImageCompressionFlagsEXT :: VkFlags;
VkImageCompressionFixedRateFlagsEXT :: VkFlags;
VkExportMetalObjectTypeFlagsEXT :: VkFlags;
VkDeviceAddressBindingFlagsEXT :: VkFlags;
VkOpticalFlowGridSizeFlagsNV :: VkFlags;
VkOpticalFlowUsageFlagsNV :: VkFlags;
VkOpticalFlowSessionCreateFlagsNV :: VkFlags;
VkOpticalFlowExecuteFlagsNV :: VkFlags;
VkFrameBoundaryFlagsEXT :: VkFlags;
VkPresentScalingFlagsKHR :: VkFlags;
VkPresentScalingFlagsEXT :: VkPresentScalingFlagsKHR;
VkPresentGravityFlagsKHR :: VkFlags;
VkPresentGravityFlagsEXT :: VkPresentGravityFlagsKHR;
VkShaderCreateFlagsEXT :: VkFlags;
VkTileShadingRenderPassFlagsQCOM :: VkFlags;
VkPhysicalDeviceSchedulingControlsFlagsARM :: VkFlags64;
VkSurfaceCreateFlagsOHOS :: VkFlags;
VkVideoCodecOperationFlagsKHR :: VkFlags;
VkVideoCapabilityFlagsKHR :: VkFlags;
VkVideoSessionCreateFlagsKHR :: VkFlags;
VkVideoSessionParametersCreateFlagsKHR :: VkFlags;
VkVideoBeginCodingFlagsKHR :: VkFlags;
VkVideoEndCodingFlagsKHR :: VkFlags;
VkVideoCodingControlFlagsKHR :: VkFlags;
VkVideoDecodeUsageFlagsKHR :: VkFlags;
VkVideoDecodeCapabilityFlagsKHR :: VkFlags;
VkVideoDecodeFlagsKHR :: VkFlags;
VkVideoDecodeH264PictureLayoutFlagsKHR :: VkFlags;
VkVideoEncodeFlagsKHR :: VkFlags;
VkVideoEncodeUsageFlagsKHR :: VkFlags;
VkVideoEncodeContentFlagsKHR :: VkFlags;
VkVideoEncodeCapabilityFlagsKHR :: VkFlags;
VkVideoEncodeFeedbackFlagsKHR :: VkFlags;
VkVideoEncodeRateControlFlagsKHR :: VkFlags;
VkVideoEncodeRateControlModeFlagsKHR :: VkFlags;
VkVideoEncodeIntraRefreshModeFlagsKHR :: VkFlags;
VkVideoChromaSubsamplingFlagsKHR :: VkFlags;
VkVideoComponentBitDepthFlagsKHR :: VkFlags;
VkVideoEncodeH264CapabilityFlagsKHR :: VkFlags;
VkVideoEncodeH264StdFlagsKHR :: VkFlags;
VkVideoEncodeH264RateControlFlagsKHR :: VkFlags;
VkVideoEncodeH265CapabilityFlagsKHR :: VkFlags;
VkVideoEncodeH265StdFlagsKHR :: VkFlags;
VkVideoEncodeH265RateControlFlagsKHR :: VkFlags;
VkVideoEncodeH265CtbSizeFlagsKHR :: VkFlags;
VkVideoEncodeH265TransformBlockSizeFlagsKHR :: VkFlags;
VkVideoEncodeAV1CapabilityFlagsKHR :: VkFlags;
VkVideoEncodeAV1StdFlagsKHR :: VkFlags;
VkVideoEncodeAV1RateControlFlagsKHR :: VkFlags;
VkVideoEncodeAV1SuperblockSizeFlagsKHR :: VkFlags;
VkAccessFlags3KHR :: VkFlags64;
VkInstance_T :: struct {}
VkInstance :: *VkInstance_T;
VkPhysicalDevice_T :: struct {}
VkPhysicalDevice :: *VkPhysicalDevice_T;
VkDevice_T :: struct {}
VkDevice :: *VkDevice_T;
VkQueue_T :: struct {}
VkQueue :: *VkQueue_T;
VkCommandBuffer_T :: struct {}
VkCommandBuffer :: *VkCommandBuffer_T;
VkDeviceMemory_T :: struct {}
VkDeviceMemory :: *VkDeviceMemory_T;
VkCommandPool_T :: struct {}
VkCommandPool :: *VkCommandPool_T;
VkBuffer_T :: struct {}
VkBuffer :: *VkBuffer_T;
VkBufferView_T :: struct {}
VkBufferView :: *VkBufferView_T;
VkImage_T :: struct {}
VkImage :: *VkImage_T;
VkImageView_T :: struct {}
VkImageView :: *VkImageView_T;
VkShaderModule_T :: struct {}
VkShaderModule :: *VkShaderModule_T;
VkPipeline_T :: struct {}
VkPipeline :: *VkPipeline_T;
VkPipelineLayout_T :: struct {}
VkPipelineLayout :: *VkPipelineLayout_T;
VkSampler_T :: struct {}
VkSampler :: *VkSampler_T;
VkDescriptorSet_T :: struct {}
VkDescriptorSet :: *VkDescriptorSet_T;
VkDescriptorSetLayout_T :: struct {}
VkDescriptorSetLayout :: *VkDescriptorSetLayout_T;
VkDescriptorPool_T :: struct {}
VkDescriptorPool :: *VkDescriptorPool_T;
VkFence_T :: struct {}
VkFence :: *VkFence_T;
VkSemaphore_T :: struct {}
VkSemaphore :: *VkSemaphore_T;
VkEvent_T :: struct {}
VkEvent :: *VkEvent_T;
VkQueryPool_T :: struct {}
VkQueryPool :: *VkQueryPool_T;
VkFramebuffer_T :: struct {}
VkFramebuffer :: *VkFramebuffer_T;
VkRenderPass_T :: struct {}
VkRenderPass :: *VkRenderPass_T;
VkPipelineCache_T :: struct {}
VkPipelineCache :: *VkPipelineCache_T;
VkPipelineBinaryKHR_T :: struct {}
VkPipelineBinaryKHR :: *VkPipelineBinaryKHR_T;
VkIndirectCommandsLayoutNV_T :: struct {}
VkIndirectCommandsLayoutNV :: *VkIndirectCommandsLayoutNV_T;
VkIndirectCommandsLayoutEXT_T :: struct {}
VkIndirectCommandsLayoutEXT :: *VkIndirectCommandsLayoutEXT_T;
VkIndirectExecutionSetEXT_T :: struct {}
VkIndirectExecutionSetEXT :: *VkIndirectExecutionSetEXT_T;
VkDescriptorUpdateTemplate_T :: struct {}
VkDescriptorUpdateTemplate :: *VkDescriptorUpdateTemplate_T;
VkDescriptorUpdateTemplateKHR :: VkDescriptorUpdateTemplate;
VkSamplerYcbcrConversion_T :: struct {}
VkSamplerYcbcrConversion :: *VkSamplerYcbcrConversion_T;
VkSamplerYcbcrConversionKHR :: VkSamplerYcbcrConversion;
VkValidationCacheEXT_T :: struct {}
VkValidationCacheEXT :: *VkValidationCacheEXT_T;
VkAccelerationStructureKHR_T :: struct {}
VkAccelerationStructureKHR :: *VkAccelerationStructureKHR_T;
VkAccelerationStructureNV_T :: struct {}
VkAccelerationStructureNV :: *VkAccelerationStructureNV_T;
VkPerformanceConfigurationINTEL_T :: struct {}
VkPerformanceConfigurationINTEL :: *VkPerformanceConfigurationINTEL_T;
VkBufferCollectionFUCHSIA_T :: struct {}
VkBufferCollectionFUCHSIA :: *VkBufferCollectionFUCHSIA_T;
VkDeferredOperationKHR_T :: struct {}
VkDeferredOperationKHR :: *VkDeferredOperationKHR_T;
VkPrivateDataSlot_T :: struct {}
VkPrivateDataSlot :: *VkPrivateDataSlot_T;
VkPrivateDataSlotEXT :: VkPrivateDataSlot;
VkCuModuleNVX_T :: struct {}
VkCuModuleNVX :: *VkCuModuleNVX_T;
VkCuFunctionNVX_T :: struct {}
VkCuFunctionNVX :: *VkCuFunctionNVX_T;
VkOpticalFlowSessionNV_T :: struct {}
VkOpticalFlowSessionNV :: *VkOpticalFlowSessionNV_T;
VkMicromapEXT_T :: struct {}
VkMicromapEXT :: *VkMicromapEXT_T;
VkShaderEXT_T :: struct {}
VkShaderEXT :: *VkShaderEXT_T;
VkTensorARM_T :: struct {}
VkTensorARM :: *VkTensorARM_T;
VkTensorViewARM_T :: struct {}
VkTensorViewARM :: *VkTensorViewARM_T;
VkDataGraphPipelineSessionARM_T :: struct {}
VkDataGraphPipelineSessionARM :: *VkDataGraphPipelineSessionARM_T;
VkDisplayKHR_T :: struct {}
VkDisplayKHR :: *VkDisplayKHR_T;
VkDisplayModeKHR_T :: struct {}
VkDisplayModeKHR :: *VkDisplayModeKHR_T;
VkSurfaceKHR_T :: struct {}
VkSurfaceKHR :: *VkSurfaceKHR_T;
VkSwapchainKHR_T :: struct {}
VkSwapchainKHR :: *VkSwapchainKHR_T;
VkDebugReportCallbackEXT_T :: struct {}
VkDebugReportCallbackEXT :: *VkDebugReportCallbackEXT_T;
VkDebugUtilsMessengerEXT_T :: struct {}
VkDebugUtilsMessengerEXT :: *VkDebugUtilsMessengerEXT_T;
VkVideoSessionKHR_T :: struct {}
VkVideoSessionKHR :: *VkVideoSessionKHR_T;
VkVideoSessionParametersKHR_T :: struct {}
VkVideoSessionParametersKHR :: *VkVideoSessionParametersKHR_T;
VkSemaphoreSciSyncPoolNV_T :: struct {}
VkSemaphoreSciSyncPoolNV :: *VkSemaphoreSciSyncPoolNV_T;
VkPrivateDataSlotCreateFlagBitsEXT :: VkPrivateDataSlotCreateFlagBits;
VkDescriptorUpdateTemplateTypeKHR :: VkDescriptorUpdateTemplateType;
VkPointClippingBehaviorKHR :: VkPointClippingBehavior;
VkQueueGlobalPriorityKHR :: VkQueueGlobalPriority;
VkQueueGlobalPriorityEXT :: VkQueueGlobalPriority;
VkTimeDomainEXT :: VkTimeDomainKHR;
VkResolveModeFlagBitsKHR :: VkResolveModeFlagBits;
VkDescriptorBindingFlagBitsEXT :: VkDescriptorBindingFlagBits;
VkSemaphoreTypeKHR :: VkSemaphoreType;
VkGeometryFlagBitsNV :: VkGeometryFlagBitsKHR;
VkGeometryInstanceFlagBitsNV :: VkGeometryInstanceFlagBitsKHR;
VkBuildAccelerationStructureFlagBitsNV :: VkBuildAccelerationStructureFlagBitsKHR;
VkCopyAccelerationStructureModeNV :: VkCopyAccelerationStructureModeKHR;
VkAccelerationStructureTypeNV :: VkAccelerationStructureTypeKHR;
VkGeometryTypeNV :: VkGeometryTypeKHR;
VkRayTracingShaderGroupTypeNV :: VkRayTracingShaderGroupTypeKHR;
VkPipelineCreationFeedbackFlagBitsEXT :: VkPipelineCreationFeedbackFlagBits;
VkSemaphoreWaitFlagBitsKHR :: VkSemaphoreWaitFlagBits;
VkLineRasterizationModeKHR :: VkLineRasterizationMode;
VkLineRasterizationModeEXT :: VkLineRasterizationMode;
VkToolPurposeFlagBitsEXT :: VkToolPurposeFlagBits;
VkAccessFlagBits2KHR :: VkAccessFlagBits2;
VkPipelineStageFlagBits2KHR :: VkPipelineStageFlagBits2;
VkHostImageCopyFlagBitsEXT :: VkHostImageCopyFlagBits;
VkFormatFeatureFlagBits2KHR :: VkFormatFeatureFlagBits2;
VkRenderingFlagBitsKHR :: VkRenderingFlagBits;
VkPipelineRobustnessBufferBehaviorEXT :: VkPipelineRobustnessBufferBehavior;
VkPipelineRobustnessImageBehaviorEXT :: VkPipelineRobustnessImageBehavior;
VkPipelineCreateFlagBits2KHR :: VkPipelineCreateFlagBits2;
VkBufferUsageFlagBits2KHR :: VkBufferUsageFlagBits2;
VkScopeNV :: VkScopeKHR;
VkComponentTypeNV :: VkComponentTypeKHR;
VkExternalMemoryHandleTypeFlagBitsKHR :: VkExternalMemoryHandleTypeFlagBits;
VkExternalMemoryFeatureFlagBitsKHR :: VkExternalMemoryFeatureFlagBits;
VkExternalSemaphoreHandleTypeFlagBitsKHR :: VkExternalSemaphoreHandleTypeFlagBits;
VkExternalSemaphoreFeatureFlagBitsKHR :: VkExternalSemaphoreFeatureFlagBits;
VkSemaphoreImportFlagBitsKHR :: VkSemaphoreImportFlagBits;
VkExternalFenceHandleTypeFlagBitsKHR :: VkExternalFenceHandleTypeFlagBits;
VkExternalFenceFeatureFlagBitsKHR :: VkExternalFenceFeatureFlagBits;
VkFenceImportFlagBitsKHR :: VkFenceImportFlagBits;
VkPeerMemoryFeatureFlagBitsKHR :: VkPeerMemoryFeatureFlagBits;
VkMemoryAllocateFlagBitsKHR :: VkMemoryAllocateFlagBits;
VkTessellationDomainOriginKHR :: VkTessellationDomainOrigin;
VkSamplerYcbcrModelConversionKHR :: VkSamplerYcbcrModelConversion;
VkSamplerYcbcrRangeKHR :: VkSamplerYcbcrRange;
VkChromaLocationKHR :: VkChromaLocation;
VkSamplerReductionModeEXT :: VkSamplerReductionMode;
VkShaderFloatControlsIndependenceKHR :: VkShaderFloatControlsIndependence;
VkSubmitFlagBitsKHR :: VkSubmitFlagBits;
VkPresentScalingFlagBitsEXT :: VkPresentScalingFlagBitsKHR;
VkPresentGravityFlagBitsEXT :: VkPresentGravityFlagBitsKHR;
VkMemoryUnmapFlagBitsKHR :: VkMemoryUnmapFlagBits;
VkDriverIdKHR :: VkDriverId;
VkCudaModuleNV_T :: struct {}
VkCudaModuleNV :: *VkCudaModuleNV_T;
VkCudaFunctionNV_T :: struct {}
VkCudaFunctionNV :: *VkCudaFunctionNV_T;
VkExternalComputeQueueNV_T :: struct {}
VkExternalComputeQueueNV :: *VkExternalComputeQueueNV_T;
